spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.database-platform=org.hibernate.dialect.PostgreSQLDialect